[package]
name = "sunny-orasis"
version = "0.1.0"
compiler = "0.12.0"
entrypoint = "main.typ"
repository = "https://github.com/edgaremy/typst-sunny-orasis"
authors = ["Edgar Remy <@edgaremy>"]
license = "MIT-0"
description = "A paper template made for the French national conference ORASIS following the author guidelines (also works for RFIAP and CAP)."
keywords = ["ORASIS", "RFIAP", "CAP", "Computer Vision", "Machine Learning"]
categories = ["paper"]
disciplines = ["computer-science", "engineering"]

[template]
path = "src"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"